# Generated by Django 4.0.2 on 2022-02-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
